parameters:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build the project - ${{parameters.buildConfiguration}}'
    inputs:
      command: 'build'
      arguments: '--no-restore --configuration ${{parameters.buildConfiguration}}'
      projects: '**/helloLearn.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Publish the project - ${{parameters.buildConfiguration}}'
    inputs:
      command: 'publish'
      projects: '**/helloLearn.csproj'
      publishWebProjects: false
      arguments: '--no-build -c Release -r win10-x64 --self-contained true --configuration ${{parameters.buildConfiguration}} --output $(Build.ArtifactStagingDirectory)/${{parameters.buildConfiguration}}'
      zipAfterPublish: true

  - task: DotNetCoreCLI@2
    displayName: 'Run unit tests - ${parameters.buildConfiguration}'
    inputs:
      command: 'test'
      arguments: '--no-build --configuration ${parameters.buildConfiguration}'
      publishTestResults: true
      projects: '**/UnitTestHelloLearn.csproj' 